// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/querier.go -destination=internal/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	db "github.com/pjhul/intent/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountCohorts mocks base method.
func (m *MockQuerier) CountCohorts(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCohorts", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCohorts indicates an expected call of CountCohorts.
func (mr *MockQuerierMockRecorder) CountCohorts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCohorts", reflect.TypeOf((*MockQuerier)(nil).CountCohorts), ctx)
}

// CountCohortsByStatus mocks base method.
func (m *MockQuerier) CountCohortsByStatus(ctx context.Context, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCohortsByStatus", ctx, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCohortsByStatus indicates an expected call of CountCohortsByStatus.
func (mr *MockQuerierMockRecorder) CountCohortsByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCohortsByStatus", reflect.TypeOf((*MockQuerier)(nil).CountCohortsByStatus), ctx, status)
}

// CreateCohort mocks base method.
func (m *MockQuerier) CreateCohort(ctx context.Context, arg db.CreateCohortParams) (db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCohort", ctx, arg)
	ret0, _ := ret[0].(db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCohort indicates an expected call of CreateCohort.
func (mr *MockQuerierMockRecorder) CreateCohort(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCohort", reflect.TypeOf((*MockQuerier)(nil).CreateCohort), ctx, arg)
}

// DeleteCohort mocks base method.
func (m *MockQuerier) DeleteCohort(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCohort", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCohort indicates an expected call of DeleteCohort.
func (mr *MockQuerierMockRecorder) DeleteCohort(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCohort", reflect.TypeOf((*MockQuerier)(nil).DeleteCohort), ctx, id)
}

// GetCohort mocks base method.
func (m *MockQuerier) GetCohort(ctx context.Context, id pgtype.UUID) (db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCohort", ctx, id)
	ret0, _ := ret[0].(db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCohort indicates an expected call of GetCohort.
func (mr *MockQuerierMockRecorder) GetCohort(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCohort", reflect.TypeOf((*MockQuerier)(nil).GetCohort), ctx, id)
}

// GetCohortByName mocks base method.
func (m *MockQuerier) GetCohortByName(ctx context.Context, name string) (db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCohortByName", ctx, name)
	ret0, _ := ret[0].(db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCohortByName indicates an expected call of GetCohortByName.
func (mr *MockQuerierMockRecorder) GetCohortByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCohortByName", reflect.TypeOf((*MockQuerier)(nil).GetCohortByName), ctx, name)
}

// GetCohortsUpdatedAfter mocks base method.
func (m *MockQuerier) GetCohortsUpdatedAfter(ctx context.Context, updatedAt pgtype.Timestamptz) ([]db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCohortsUpdatedAfter", ctx, updatedAt)
	ret0, _ := ret[0].([]db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCohortsUpdatedAfter indicates an expected call of GetCohortsUpdatedAfter.
func (mr *MockQuerierMockRecorder) GetCohortsUpdatedAfter(ctx, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCohortsUpdatedAfter", reflect.TypeOf((*MockQuerier)(nil).GetCohortsUpdatedAfter), ctx, updatedAt)
}

// ListActiveCohorts mocks base method.
func (m *MockQuerier) ListActiveCohorts(ctx context.Context) ([]db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveCohorts", ctx)
	ret0, _ := ret[0].([]db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveCohorts indicates an expected call of ListActiveCohorts.
func (mr *MockQuerierMockRecorder) ListActiveCohorts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveCohorts", reflect.TypeOf((*MockQuerier)(nil).ListActiveCohorts), ctx)
}

// ListCohorts mocks base method.
func (m *MockQuerier) ListCohorts(ctx context.Context, arg db.ListCohortsParams) ([]db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohorts", ctx, arg)
	ret0, _ := ret[0].([]db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohorts indicates an expected call of ListCohorts.
func (mr *MockQuerierMockRecorder) ListCohorts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohorts", reflect.TypeOf((*MockQuerier)(nil).ListCohorts), ctx, arg)
}

// ListCohortsByStatus mocks base method.
func (m *MockQuerier) ListCohortsByStatus(ctx context.Context, arg db.ListCohortsByStatusParams) ([]db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortsByStatus", ctx, arg)
	ret0, _ := ret[0].([]db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortsByStatus indicates an expected call of ListCohortsByStatus.
func (mr *MockQuerierMockRecorder) ListCohortsByStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortsByStatus", reflect.TypeOf((*MockQuerier)(nil).ListCohortsByStatus), ctx, arg)
}

// UpdateCohort mocks base method.
func (m *MockQuerier) UpdateCohort(ctx context.Context, arg db.UpdateCohortParams) (db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCohort", ctx, arg)
	ret0, _ := ret[0].(db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCohort indicates an expected call of UpdateCohort.
func (mr *MockQuerierMockRecorder) UpdateCohort(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCohort", reflect.TypeOf((*MockQuerier)(nil).UpdateCohort), ctx, arg)
}

// UpdateCohortStatus mocks base method.
func (m *MockQuerier) UpdateCohortStatus(ctx context.Context, arg db.UpdateCohortStatusParams) (db.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCohortStatus", ctx, arg)
	ret0, _ := ret[0].(db.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCohortStatus indicates an expected call of UpdateCohortStatus.
func (mr *MockQuerierMockRecorder) UpdateCohortStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCohortStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateCohortStatus), ctx, arg)
}
