// Code generated by MockGen. DO NOT EDIT.
// Source: internal/inserter/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/inserter/interfaces.go -destination=internal/mocks/mock_inserter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	inserter "github.com/pjhul/intent/internal/inserter"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchPreparer is a mock of BatchPreparer interface.
type MockBatchPreparer struct {
	ctrl     *gomock.Controller
	recorder *MockBatchPreparerMockRecorder
	isgomock struct{}
}

// MockBatchPreparerMockRecorder is the mock recorder for MockBatchPreparer.
type MockBatchPreparerMockRecorder struct {
	mock *MockBatchPreparer
}

// NewMockBatchPreparer creates a new mock instance.
func NewMockBatchPreparer(ctrl *gomock.Controller) *MockBatchPreparer {
	mock := &MockBatchPreparer{ctrl: ctrl}
	mock.recorder = &MockBatchPreparerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchPreparer) EXPECT() *MockBatchPreparerMockRecorder {
	return m.recorder
}

// PrepareBatch mocks base method.
func (m *MockBatchPreparer) PrepareBatch(ctx context.Context, query string) (inserter.InserterBatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareBatch", ctx, query)
	ret0, _ := ret[0].(inserter.InserterBatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareBatch indicates an expected call of PrepareBatch.
func (mr *MockBatchPreparerMockRecorder) PrepareBatch(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareBatch", reflect.TypeOf((*MockBatchPreparer)(nil).PrepareBatch), ctx, query)
}

// MockInserterBatch is a mock of InserterBatch interface.
type MockInserterBatch struct {
	ctrl     *gomock.Controller
	recorder *MockInserterBatchMockRecorder
	isgomock struct{}
}

// MockInserterBatchMockRecorder is the mock recorder for MockInserterBatch.
type MockInserterBatchMockRecorder struct {
	mock *MockInserterBatch
}

// NewMockInserterBatch creates a new mock instance.
func NewMockInserterBatch(ctrl *gomock.Controller) *MockInserterBatch {
	mock := &MockInserterBatch{ctrl: ctrl}
	mock.recorder = &MockInserterBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInserterBatch) EXPECT() *MockInserterBatchMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockInserterBatch) Append(args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Append", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockInserterBatchMockRecorder) Append(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockInserterBatch)(nil).Append), args...)
}

// Send mocks base method.
func (m *MockInserterBatch) Send() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send")
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockInserterBatchMockRecorder) Send() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockInserterBatch)(nil).Send))
}
