// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/cohort/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/cohort/service.go -destination=internal/mocks/mock_producer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cohort "github.com/pjhul/intent/internal/domain/cohort"
	gomock "go.uber.org/mock/gomock"
)

// MockCohortProducer is a mock of CohortProducer interface.
type MockCohortProducer struct {
	ctrl     *gomock.Controller
	recorder *MockCohortProducerMockRecorder
	isgomock struct{}
}

// MockCohortProducerMockRecorder is the mock recorder for MockCohortProducer.
type MockCohortProducerMockRecorder struct {
	mock *MockCohortProducer
}

// NewMockCohortProducer creates a new mock instance.
func NewMockCohortProducer(ctrl *gomock.Controller) *MockCohortProducer {
	mock := &MockCohortProducer{ctrl: ctrl}
	mock.recorder = &MockCohortProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortProducer) EXPECT() *MockCohortProducerMockRecorder {
	return m.recorder
}

// ProduceCohortDefinition mocks base method.
func (m *MockCohortProducer) ProduceCohortDefinition(ctx context.Context, c *cohort.Cohort) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceCohortDefinition", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceCohortDefinition indicates an expected call of ProduceCohortDefinition.
func (mr *MockCohortProducerMockRecorder) ProduceCohortDefinition(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceCohortDefinition", reflect.TypeOf((*MockCohortProducer)(nil).ProduceCohortDefinition), ctx, c)
}

// ProduceCohortDeletion mocks base method.
func (m *MockCohortProducer) ProduceCohortDeletion(ctx context.Context, cohortID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceCohortDeletion", ctx, cohortID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceCohortDeletion indicates an expected call of ProduceCohortDeletion.
func (mr *MockCohortProducerMockRecorder) ProduceCohortDeletion(ctx, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceCohortDeletion", reflect.TypeOf((*MockCohortProducer)(nil).ProduceCohortDeletion), ctx, cohortID)
}
