// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/cohort/recompute_worker.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/cohort/recompute_worker.go -destination=internal/mocks/mock_clickhouse.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	cohort "github.com/pjhul/intent/internal/domain/cohort"
	gomock "go.uber.org/mock/gomock"
)

// MockClickHouseClient is a mock of ClickHouseClient interface.
type MockClickHouseClient struct {
	ctrl     *gomock.Controller
	recorder *MockClickHouseClientMockRecorder
	isgomock struct{}
}

// MockClickHouseClientMockRecorder is the mock recorder for MockClickHouseClient.
type MockClickHouseClientMockRecorder struct {
	mock *MockClickHouseClient
}

// NewMockClickHouseClient creates a new mock instance.
func NewMockClickHouseClient(ctrl *gomock.Controller) *MockClickHouseClient {
	mock := &MockClickHouseClient{ctrl: ctrl}
	mock.recorder = &MockClickHouseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickHouseClient) EXPECT() *MockClickHouseClientMockRecorder {
	return m.recorder
}

// PrepareBatch mocks base method.
func (m *MockClickHouseClient) PrepareBatch(ctx context.Context, query string) (cohort.Batch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareBatch", ctx, query)
	ret0, _ := ret[0].(cohort.Batch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareBatch indicates an expected call of PrepareBatch.
func (mr *MockClickHouseClientMockRecorder) PrepareBatch(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareBatch", reflect.TypeOf((*MockClickHouseClient)(nil).PrepareBatch), ctx, query)
}

// Query mocks base method.
func (m *MockClickHouseClient) Query(ctx context.Context, query string, args ...any) (cohort.RowScanner, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(cohort.RowScanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockClickHouseClientMockRecorder) Query(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockClickHouseClient)(nil).Query), varargs...)
}

// MockRowScanner is a mock of RowScanner interface.
type MockRowScanner struct {
	ctrl     *gomock.Controller
	recorder *MockRowScannerMockRecorder
	isgomock struct{}
}

// MockRowScannerMockRecorder is the mock recorder for MockRowScanner.
type MockRowScannerMockRecorder struct {
	mock *MockRowScanner
}

// NewMockRowScanner creates a new mock instance.
func NewMockRowScanner(ctrl *gomock.Controller) *MockRowScanner {
	mock := &MockRowScanner{ctrl: ctrl}
	mock.recorder = &MockRowScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRowScanner) EXPECT() *MockRowScannerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRowScanner) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRowScannerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRowScanner)(nil).Close))
}

// Next mocks base method.
func (m *MockRowScanner) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockRowScannerMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRowScanner)(nil).Next))
}

// Scan mocks base method.
func (m *MockRowScanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockRowScannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRowScanner)(nil).Scan), dest...)
}

// MockBatch is a mock of Batch interface.
type MockBatch struct {
	ctrl     *gomock.Controller
	recorder *MockBatchMockRecorder
	isgomock struct{}
}

// MockBatchMockRecorder is the mock recorder for MockBatch.
type MockBatchMockRecorder struct {
	mock *MockBatch
}

// NewMockBatch creates a new mock instance.
func NewMockBatch(ctrl *gomock.Controller) *MockBatch {
	mock := &MockBatch{ctrl: ctrl}
	mock.recorder = &MockBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatch) EXPECT() *MockBatchMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockBatch) Append(args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Append", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockBatchMockRecorder) Append(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockBatch)(nil).Append), args...)
}

// Send mocks base method.
func (m *MockBatch) Send() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send")
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockBatchMockRecorder) Send() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockBatch)(nil).Send))
}

// MockCohortGetter is a mock of CohortGetter interface.
type MockCohortGetter struct {
	ctrl     *gomock.Controller
	recorder *MockCohortGetterMockRecorder
	isgomock struct{}
}

// MockCohortGetterMockRecorder is the mock recorder for MockCohortGetter.
type MockCohortGetterMockRecorder struct {
	mock *MockCohortGetter
}

// NewMockCohortGetter creates a new mock instance.
func NewMockCohortGetter(ctrl *gomock.Controller) *MockCohortGetter {
	mock := &MockCohortGetter{ctrl: ctrl}
	mock.recorder = &MockCohortGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortGetter) EXPECT() *MockCohortGetterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCohortGetter) GetByID(ctx context.Context, id uuid.UUID) (*cohort.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*cohort.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCohortGetterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCohortGetter)(nil).GetByID), ctx, id)
}
