// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAllProjects(ctx context.Context) (int64, error)
	CountCohorts(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountCohortsByStatus(ctx context.Context, arg CountCohortsByStatusParams) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountProjects(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	CreateCohort(ctx context.Context, arg CreateCohortParams) (CreateCohortRow, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteCohort(ctx context.Context, id pgtype.UUID) error
	DeleteOrganization(ctx context.Context, id pgtype.UUID) error
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	GetCohort(ctx context.Context, id pgtype.UUID) (GetCohortRow, error)
	GetCohortByName(ctx context.Context, arg GetCohortByNameParams) (GetCohortByNameRow, error)
	GetCohortsUpdatedAfter(ctx context.Context, updatedAt pgtype.Timestamptz) ([]GetCohortsUpdatedAfterRow, error)
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	ListActiveCohorts(ctx context.Context, projectID pgtype.UUID) ([]ListActiveCohortsRow, error)
	ListAllActiveCohorts(ctx context.Context) ([]ListAllActiveCohortsRow, error)
	ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]Project, error)
	ListCohorts(ctx context.Context, arg ListCohortsParams) ([]ListCohortsRow, error)
	ListCohortsByStatus(ctx context.Context, arg ListCohortsByStatusParams) ([]ListCohortsByStatusRow, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	UpdateCohort(ctx context.Context, arg UpdateCohortParams) (UpdateCohortRow, error)
	UpdateCohortStatus(ctx context.Context, arg UpdateCohortStatusParams) (UpdateCohortStatusRow, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
