// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCohorts(ctx context.Context) (int64, error)
	CountCohortsByStatus(ctx context.Context, status string) (int64, error)
	CreateCohort(ctx context.Context, arg CreateCohortParams) (Cohort, error)
	DeleteCohort(ctx context.Context, id pgtype.UUID) error
	GetCohort(ctx context.Context, id pgtype.UUID) (Cohort, error)
	GetCohortByName(ctx context.Context, name string) (Cohort, error)
	GetCohortsUpdatedAfter(ctx context.Context, updatedAt pgtype.Timestamptz) ([]Cohort, error)
	ListActiveCohorts(ctx context.Context) ([]Cohort, error)
	ListCohorts(ctx context.Context, arg ListCohortsParams) ([]Cohort, error)
	ListCohortsByStatus(ctx context.Context, arg ListCohortsByStatusParams) ([]Cohort, error)
	UpdateCohort(ctx context.Context, arg UpdateCohortParams) (Cohort, error)
	UpdateCohortStatus(ctx context.Context, arg UpdateCohortStatusParams) (Cohort, error)
}

var _ Querier = (*Queries)(nil)
